language: go

go:
  - 1.14.x
  - 1.15.x
  - master

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - cp config/client/sap_client.yaml internal/client/
  - cp config/server/sap_server.yaml internal/server/
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go build cmd/server/server.go
  - go build cmd/client/client.go
  - go build cmd/web/web.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
